server:
  port : 8081

spring:
  mail:
    host: smtp.gmail.com
    username: asishpani19@gmail.com
    password: qyqxxickqnxjfanp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
